# VARIABLES
@baseUrl = http://localhost:3333

# Get rooms

# @name getRooms

GET {{baseUrl}}/rooms

###

# CREATE ROOM
# @name createRoom

POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "teste3",
    "description": "TESTE4"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# GET ROOM QUESTION

# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# CREATE QUESTION

# @name postQuestion
POST {{baseUrl}}/rooms/111179ed-6778-47da-3cb9-f8813aabe33b/questions
Content-Type: application/json

{
    "question": "O que é Vue.js e sua diferença ao Angular?"
}
